ec2-launch-using-terraform-github-action-workflow

diff --git a/.github/workflows/Ec2.yml b/.github/workflows/Ec2.yml
--- a/.github/workflows/Ec2.yml
+++ b/.github/workflows/Ec2.yml
@@ -27,6 +27,10 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1
 
+      - name: Verify Directory Structure
+        run: ls -la && ls -la terraform || echo "Terraform folder missing!"
+
+
       - name: Initialize Terraform
         run: terraform init
         working-directory: ./terraform/ec2  # ✅ Corrected path
